version: "3.9"

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

  php:
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
    volumes:
      - ../backend:/var/www/html
    working_dir: /var/www/html

  nginx:
    build:
      context: ../docker/nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../backend:/var/www/html:ro
      - ../docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  frontend:
    build:
      context: ..
      dockerfile: docker/angular/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ../frontend/app:/app
      - /app/node_modules
    command: sh -c "npm install && ng serve --host 0.0.0.0 --port 4200 --poll 2000"
    depends_on:
      - php

volumes:
  mysql_data:
  vendor:
  storage:
  node_modules: